owner: Wardfinder
repo: status

sites:
  - name: Website
    url: https://wardfinder.com
  - name: App
    url: https://app.wardfinder.com
  - name: API
    url: https://api.wardfinder.com
  - name: Tools
    url: https://tools.wardfinder.com

assignees:
  - DeclanChidlow

status-website:
  cname: status.wardfinder.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  themeUrl: https://status.wardfinder.com/theme.css
  name: Status | Wardfinder
  introTitle: "Wardfinder Service Status"
  introMessage: The current and historical statuses of Wardfinder services.
  navbar:
    - title: Website
      href: https://wardfinder.com
